version: '3.4'

services:
  temancurhatmube:
    image: temancurhatmube
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 7009:7009
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
